# Generated by Django 2.0.1 on 2018-01-09 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
