# Generated by Django 2.0.1 on 2018-01-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Client'),
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product'),
        ),
    ]
