version: '2'
services:
  mysql-db:
    container_name: mysql-db
    build: .
    ports:
      - "3306:3306"
    volumes:
      - test-mysql-db:/var/lib/mysql
      - test-run:/run/mysqld

volumes:
  test-mysql-db:
  test-run: